global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "fastapi"
    metrics_path: /metrics
    static_configs:
      - targets: ["dna_api:8000"]
  
  - job_name: "node"
    static_configs:
      - targets: ["node-exporter:9100"]


  - job_name: "postgres"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  