name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t forensic-dna-api -f infra/Dockerfile .

      # ðŸ”¥ CI TEST STEP STARTS HERE
      - name: Run container
        run: |
          docker run -d -p 8000:8000 --name dna_api_test forensic-dna-api

      - name: Wait for API
        run: sleep 10

      - name: Smoke test (/docs)
        run: |
          curl --fail http://localhost:8000/health

      - name: Health check (API)
        run: |
          curl --fail http://localhost:8000/health

      - name: Health check (DB)
        run: |
          curl --fail http://localhost:8000/health/db

      - name: Stop container
        run: docker stop dna_api_test
